

### single movie

GET http://localhost:1234/api/v1/movies/814cc872-e324-11ee-a74c-bc5ff4400066

###
#  GET http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

### Search by genre
GET http://localhost:1234/api/v1/movies?genre=ACTION

### New movie
POST http://localhost:1234/api/v1/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM user;",
    "title": "The Marvels",
    "year": 2023,
    "director": "Nia DaCosta",
    "duration": 105,
    "poster": "https://m.media-amazon.com/images/M/MV5BM2U2YWU5NWMtOGI2Ni00MGMwLWFkNjItMjgyZWMxNjllNTMzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_QL75_UX190_CR0,0,190,281_.jpg",
    "genre": [
        "Action",
        "Adventure",
        "Sci-Fi"
    ],
    "rate": 7.3
}

### Update movie
PATCH http://localhost:1234/api/v1/movies/2eff697c-e8a6-11ee-a74c-bc5ff4400066
Content-Type: application/json

{
    "year": 2023,
    "title": "The Marvels",
    "duration": 105,
    "genre": [
        "Action",
        "Adventure",
        "Sci-Fi"
    ]
}

### Delete movie
DELETE http://localhost:1234/api/v1/movies/b81c839d-e3e6-11ee-a74c-bc5ff4400066


### all movies
GET http://localhost:1234/api/v1/movies